### ISSUE TITLE
105.组织→组织成员tab 的一览，列排序提示的变化和其它一览不同

### ISSUE THREAD

**Issue by freezxb** [oizhaolei/spa-wiki#105]
组织→组织成员tab 的一览，列头排序提示的变化和其它一览不同。
・组织→组织成员 一览列头排序提示的变化是，初始时，把鼠标移到"用户名“这列头，提示”点击升序“，点击后，数据升序排列，提示立刻变化为"点击降序”。
・其它的一览，例如群组一览，初始时，把鼠标移到“群组编号”这列，提示"点击升序"，点击后，数据升序排列，但提示消失了。必须把鼠标移到列头外，再移回来，提示才会重新出现 "点击降序"。

**Comment by liujiuyi** [comment]
组织成员tab是本地数据，其它是远端数据，研究了一下好像和这个有关，实在改不了，要不就这样吧 @freezxb

**Comment by freezxb** [comment]
现状也可以，关闭此票。
