### ISSUE TITLE
117.指标面板->上月工单 中，点击状态列中的记录后，显示的数据远多于预期

### ISSUE THREAD

**Issue by freezxb** [oizhaolei/spa-wiki#117]
如下图，用户freexb(身份为操作者)，在 指标面板->上月工单中，"对应中"的显示仅有1件。
但是点击"对应中"，进入工单一览后，列表中显示14件，而且很多并不属于现用户freexb。
备注：点击其它状态(暂停、完成、取消)，也有相同问题。
![analysisLastMonthLinkList](https://user-images.githubusercontent.com/18024406/101305309-5438ad00-387d-11eb-87b0-a3d0d1977073.jpg)

**Comment by freezxb** [comment]
2020/12/08 zxb 追记：今天用管理者测了一下，也有问题：指标面板->上月工单 中，各状态的件数，和点击link后显示的一览中的件数不符。如下图，指标面板->上月工单->完成为27件，但点击完成显示的列表中，显示29件。
![analysisLastMonthTicketLinkList](https://user-images.githubusercontent.com/18024406/101450452-89202f00-3965-11eb-818a-09d4a8d3f6da.jpg)

**Comment by liujiuyi** [comment]
@freezxb 这个功能貌似取消了

**Comment by freezxb** [comment]
21/03/30 确认结果：link已删除，关闭此票。
