### ISSUE TITLE
135.用户一览页面的列中多了一个 "Line ID" 

### ISSUE THREAD

**Issue by freezxb** [oizhaolei/spa-wiki#135]
用户一览页面中，多了一个Line ID列。我记得以前没有这个列，而且这个列意义不明。
![userListLineIdCol](https://user-images.githubusercontent.com/18024406/109739366-7768c380-7c04-11eb-9c0e-bd58774b80e7.jpg)

**Comment by liujiuyi** [comment]
![image](https://user-images.githubusercontent.com/8744016/109741206-8ef57b80-7c07-11eb-9515-375aeaf09446.png)
设置里面绑定line之后就会有这个值，为了line登录使用的 @freezxb

**Comment by freezxb** [comment]
撤销此票。
