### ISSUE TITLE
151.用户view-->备注tab-->项目  一列的排序，好像反了

### ISSUE THREAD

**Issue by freezxb** [oizhaolei/spa-wiki#151]
![userViewSnippetPrjOrdErr](https://user-images.githubusercontent.com/18024406/112955473-0b7d6a80-9172-11eb-8339-7dd396d9c71a.jpg)

**Comment by liujiuyi** [comment]
这个排序没办法按照项目名字排序，取消这个排序了

**Comment by freezxb** [comment]
21/04/01 确认OK，取消此列的排序。
