### ISSUE TITLE
152.删除项目后，被删项目的 活动记录出现异常

### ISSUE THREAD

**Issue by freezxb** [oizhaolei/spa-wiki#152]
创建一个项目，或者 修改一个项目。 在指标面板-->活动 里，和 用户view-->活动 里，都会出现 相应的记录(创建项目 、 修改项目)。但是将项目删除后，被删项目的活动记录发生异常：
1.指标面板-->活动 里，被删项目的所有活动全部消失。
2.用户view-->活动 里，仅剩余 删除项目 的记录。
![activityDelPrjErr](https://user-images.githubusercontent.com/18024406/112958527-256c7c80-9175-11eb-8bed-4c3a302eb5e8.jpg)

**Comment by liujiuyi** [comment]
已修改为删除后清理掉所有的活动记录，请确认

**Comment by freezxb** [comment]
21/04/01 确认OK：删除项目后，被删项目的所有活动也被全部删除。
