### ISSUE TITLE
45.工作流view里工单一览里的 目标时间/经过时间一列仅显示经过时间

### ISSUE THREAD

**Issue by freezxb** [oizhaolei/spa-wiki#45]
工作流view-->工单一览-->目标时间/经过时间 一列的柱状图，仅显示经过时间，未显示目标时间。与列名不符。
![flowViewTicketTimeCol](https://user-images.githubusercontent.com/18024406/97959273-f92d1980-1de9-11eb-8085-472906a1825e.jpg)

**Comment by oizhaolei** [comment]
目标时间，取错了。

flow => flow_snapshot

**Comment by freezxb** [comment]
2020/11/12 zxb 确认OK。
