### ISSUE TITLE
50.指标面板的 常用工作流，怎么才能有数据呢？

### ISSUE THREAD

**Issue by freezxb** [oizhaolei/spa-wiki#50]
指标面板的 常用工作流，怎么才能有数据呢？在测试期间，这里一直没数据。
![analysisFlowFrequentlyUsed](https://user-images.githubusercontent.com/18024406/97965159-e704a880-1df4-11eb-94bf-113431ecb329.jpg)

**Comment by Xinaction** [comment]
现在没有这个了吗？

**Comment by Xinaction** [comment]
代码里确认了已经被注释掉了
![image](https://user-images.githubusercontent.com/1531173/109895932-122bd580-7ccb-11eb-93c7-f8136e0f1576.png)

**Comment by freezxb** [comment]
21/03/26 确认结果：指标面板里已经删除了 常用工作流。
