### ISSUE TITLE
72.项目->设置->会员->现有成员和群组 的删除按钮失效

### ISSUE THREAD

**Issue by freezxb** [oizhaolei/spa-wiki#72]
项目->设置->会员->现有成员和群组 的删除按钮失效。是否和bug-63的修改有关呢？
![projMebDelBtn](https://user-images.githubusercontent.com/18024406/98899062-dd143100-24e9-11eb-9eb3-15077f9b0772.jpg)

**Comment by oizhaolei** [comment]
不是

弹出消息的issue导致的

**Comment by freezxb** [comment]
2020/11/13 zxb 确认OK：remove按钮动作恢复正常了。
