### ISSUE TITLE
90.指标面板->上个月的工单 这部分，无数据时的提示语言和系统不一致

### ISSUE THREAD

**Issue by freezxb** [oizhaolei/spa-wiki#90]
指标面板->上个月的工单 这部分，在系统为中文或英文版时，其提示仍未日语："チケット情報は存在しません。"。
![lastMonthTicketNoDataTipLang](https://user-images.githubusercontent.com/18024406/99217926-23cc9880-2814-11eb-84bd-4093f593054f.jpg)

**Comment by oizhaolei** [comment]
都改成en了

**Comment by freezxb** [comment]
2020/11/17 zxb 确认OK。
