### ISSUE TITLE
96.项目->设置->会员  里，当群组数据为空时，群组的标题和群组列表区域均不显示

### ISSUE THREAD

**Issue by freezxb** [oizhaolei/spa-wiki#96]
项目->设置->会员 里，如下图，
・当成员和群组都有数据时，成员和群组的标题以及列表都正常显示。
・当成员和群组都无数据时，二者的显示差异很大，差异参见下述。原本的设计就是如此吗？
 　→成员的标题依旧显示，列表区域显示"暂无数据"。
 　→群组的标题消失，列表区域也空白。
![projMebNoGrp](https://user-images.githubusercontent.com/18024406/99353863-5643c780-28e0-11eb-903a-31420f42e792.jpg)

**Comment by oizhaolei** [comment]
2个表格，数据为空的话，各自都显示Empty View

**Comment by freezxb** [comment]
2020/11/18 zxb 确认OK：群组无数据时也显示标题和"暂无数据"(Empty View)。
