### ISSUE TITLE
97.项目->设置->会员->关于 "台账管理员" 的疑问

### ISSUE THREAD

**Issue by freezxb** [oizhaolei/spa-wiki#97]
项目P1->设置->会员中，若赋予所邀成员U1的权限为
台账管理员、或 台账管理员 + 工作流管理员、或 台账管理员 + 工单管理员、或 台账管理员 + 游客，
则若以用户U1登录系统并进入项目P1，此用户U1具有台账的上传和下载的权限，但不具有台账的新建和删除的权限。

原本设计就是这样的吗？

**Comment by oizhaolei** [comment]
游客，因为有访问某个project的权限，可以看到ledger的数据，不能增删改
只有project和ledger的权限的人可以增删改

UI上需要处理一下，前后端的判断需要一致

**Comment by oizhaolei** [comment]
修改了一下，请测试看看

**Comment by freezxb** [comment]
现在无法新建台账了。暂时把fixed去掉了。等台账新建功能恢复后 再行确认。

**Comment by oizhaolei** [comment]
Duplicate of #98

**Comment by freezxb** [comment]
2021/03/01 确认NG：
项目P1->设置->会员中，若赋予所邀成员U1的权限为
台账管理员、或 台账管理员 + 工作流管理员、或 台账管理员 + 工单管理员、或 台账管理员 + 游客  时，
此成员登陆后，只有活动和备注两个tab页能显示，其它页面显示均异常。
![prjMebShowTabErr](https://user-images.githubusercontent.com/18024406/109443362-52921600-7a75-11eb-9de3-7e2cbc017108.jpg)

**Comment by freezxb** [comment]
2021/03/02 测试NG(※这个也是权限相关的问题，要不讨论后再修改吧。)：
1.台账管理员可以上传下载，但是无法删除和新建台账：NG
2.游客只能看到总览tab、活动和备注，其它的tab均看不到：NG

**Comment by liujiuyi** [comment]
@freezxb 这两个问题至少目前看不算bug
1，新建台账需要project权限
2，现在分为'flow.*', 'guest', 'ledger.*', 'project.*', 'ticket.*'这些权限，除了guest每个权限对应相应的功能，没有权限就看到相应tab里面的数据也是对的

等待讨论结果吧

**Comment by freezxb** [comment]
如果建台账需要  项目和台账  两项权限的话，又产生了no149的问题。

**Comment by liujiuyi** [comment]
参照149，两个权限不发生关系

**Comment by freezxb** [comment]
21/03/29 参照№149，确认OK，关闭此票。
